# Generated by Django 3.2.13 on 2022-05-24 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(help_text='Enter Product Name', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description', null=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('price', models.FloatField(help_text='Enter Product Price per unit')),
                ('quantity', models.IntegerField(help_text='Enter Product Quantity in stock')),
                ('product_category', models.CharField(choices=[('Grocery', 'Grocery'), ('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Toys', 'Toys')], max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
