# Generated by Django 3.2.13 on 2022-05-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Enter Product Description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Toys', 'Toys')], max_length=50, null=True),
        ),
    ]
